### ISSUE TITLE
Do you have time to make a V2 beta3 version?

### ISSUE THREAD

**Issue by DrJeff** [mezz64/appdaemon-docker#1]
Can you create a docker for the V2 beta3?
https://community.home-assistant.io/t/announcement-hadashboard-v2-beta3/14504

I assume it is alot more work than you may want to do but thought I would ask before I try my hand at this.

Thanks,
Jeff

**Comment by mezz64** [comment]
It already exists under the ```dash``` tag on docker hub. :)

**Comment by DrJeff** [comment]
Woot woot!
Thanks

**Comment by DrJeff** [comment]
Sorry but how do I use TAGS in unRAID? I know on a Mac but not on unRAID

**Comment by DrJeff** [comment]
Nevermind was the same I think.... add 
```
:dash
```
